add command line interface for library
collinsmezie/school-library pull request #4
Opened 2022-07-02 20:42 UTC by collinsmezie

List all books.
List all people.
Create a person (teacher or student, not a plain Person).
Create a book.
Create a rental.
List all rentals for a given person id.

FUNCTIONS:
Present the user with a list of options to perform.
Lets users choose an option.
If needed, ask for parameters for the option.
Have a way to quit the app.

2022-07-02 21:23 UTC, danmainah requested changes
Hi @collinsmezie , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good PR and Description


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-02 21:23 UTC, danmainah commented on app.rb
> +  end
- [ ] Kindly move these functions into your `main.rb` file, this is a project requirement.
- [ ] Also kindly ensure your app is functioning am getting this error from one of your files when I run it locally
![image](https://user-images.githubusercontent.com/61408860/177016501-0c5bde73-5b1c-4650-a01a-0ea8c8c11794.png)

2022-07-04 09:20 UTC, rukundoeric requested changes
Hi @collinsmezie, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 


## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-04 09:20 UTC, rukundoeric commented on app.rb
> +  end
- [ ] <b>REQUIRED:</b> You still haven't fixed some issues raised from the previous review.
  - When I try to create a person with type teacher, the app throws an error:
    ![Screenshot(15)](https://user-images.githubusercontent.com/45217364/177123761-03f481c0-155c-4bf3-ae3f-897aa4c13b79.png)
  - When I try to create a person with student type, the app can't be able to set a permission. 
  ![Screenshot(16)](https://user-images.githubusercontent.com/45217364/177124454-548462e3-2bfc-4ee6-8720-493742e7e07d.png)

2022-07-04 13:05 UTC, ShoiraTa requested changes
Hi @collinsmezie ,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

**First let me to point out:**

- Great commit history! ✔️ 
- You passed all the Linters! ✔️ 
- Professional pull request! ✔️ 

Keep on coding, good job so far! :clap:

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear by mentioning my Github username.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-04 13:05 UTC, ShoiraTa commented on app.rb
> +    else
- [ ] I still cannot add a teacher, I tried to check the reason, and found that you added create_student method but did not add create_teacher method. So when I select create_teacher method, app just cannot find the method to run. Please add create_teacher to make the app work. You can start from checking the code below:  


```
  def create_teacher
    puts 'Enter age: '
    age = gets.chomp
    puts 'Enter name: '
    name = gets.chomp
    puts "'Has parent permission? [Y/N]: '"
    permission = gets.chomp
      teacher = Teacher.new(age, name, parent_permission: false)
      @person.push(teacher)
  end

```

After adding the missing method, please make sure that it works properly (name, age, and etc fields are added in object)

2022-07-04 14:13 UTC, dasileker approved these changes
### **Hi @collinsmezie,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-04 14:19 UTC, merged